### ISSUE TITLE
name clash with loomio-org

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio_org_plugin#1]
we have two repos with similar names, loomio_org (this one) and loomio-org  (riches handbook for the loomio organisation)

I'm going to request both repos change their name.

Can we call this loomio.org-plugin?

**Comment by gdpelican** [comment]
Dots in repo names make me a little weirded out, but am not married to (or even fond of) this repo name. How about

loomio_org_plugin
loomio_dot_org
loomio_org_instance
loomio_mothership :alien:
loomio_marketing
?

**Comment by rdbartlett** [comment]
mothership is cool! 

is there any sense in namespaceing plugin repos in our github org? like loomio/plugin_mothership loomio/plugin_slack etc?

**Comment by robguthrie** [comment]
loomio_org_plugin seems fine to me. I'd rather not include distracting
terms (mothership etc) in repo names..
